import { getProvincialTaxRate } from '@/lib/provinceData';

// Helper to build a complete preset with tax rate auto-calculated
function makePreset(overrides) {
    const province = overrides.province || 'ON';
    const bracket = overrides.taxBracket || 'top';
    const taxRate = getProvincialTaxRate(province, bracket) || 53.53;

    return {
        initialMortgage: 1091000,
        mortgageRate: 3.65,
        mortgageType: 'fixed',
        amortYears: 30,
        helocRate: 4.70,
        province: 'ON',
        taxBracket: 'top',
        taxRate,
        annualReturn: 7,
        growthRate: 7,
        dividendYield: 1.6,
        inflationRate: 2.0,
        initialTfsa: 0,
        tfsaRoomYear1: 42000,
        annualTfsaIncrease: 7000,
        tfsaFundingSource: 'heloc',
        rrspYear1: 50000,
        rrspOngoing: 25000,
        rrspFundingSource: 'heloc',
        retirementTaxRate: 20,
        initialHelocAvailable: 300000,
        ...overrides,
    };
}

export const PRESETS = [
    {
        id: 'vanilla-sm',
        name: 'Vanilla SM',
        icon: '🔄',
        description: 'Pure SM — no TFSA/RRSP, no initial HELOC',
        formData: makePreset({
            initialMortgage: 500000,
            mortgageRate: 4.5,
            amortYears: 25,
            helocRate: 5.5,
            taxBracket: 'mid',
            annualReturn: 7,
            growthRate: 7,
            dividendYield: 2.0,
            initialTfsa: 0,
            tfsaRoomYear1: 0,
            annualTfsaIncrease: 0,
            tfsaFundingSource: 'savings',
            rrspYear1: 0,
            rrspOngoing: 0,
            rrspFundingSource: 'savings',
            retirementTaxRate: 20,
            initialHelocAvailable: 0,
        }),
    },
    {
        id: 'first-time',
        name: 'First-Time Buyer',
        icon: '🏡',
        description: '$600K mortgage, moderate leverage',
        formData: makePreset({
            initialMortgage: 600000,
            mortgageRate: 4.5,
            amortYears: 25,
            helocRate: 5.5,
            taxBracket: 'high',
            annualReturn: 7,
            growthRate: 7,
            dividendYield: 1.5,
            initialTfsa: 0,
            tfsaRoomYear1: 42000,
            annualTfsaIncrease: 7000,
            tfsaFundingSource: 'savings',
            rrspYear1: 20000,
            rrspOngoing: 10000,
            rrspFundingSource: 'savings',
            retirementTaxRate: 20,
            initialHelocAvailable: 80000,
        }),
    },
    {
        id: 'move-up',
        name: 'Move-Up Buyer',
        icon: '🏠',
        description: '$1.1M mortgage, full SM strategy',
        formData: makePreset({
            initialMortgage: 1091000,
            mortgageRate: 3.65,
            amortYears: 30,
            helocRate: 4.70,
            taxBracket: 'top',
            annualReturn: 7,
            growthRate: 7,
            dividendYield: 1.6,
            initialTfsa: 955 * 39.79,
            tfsaRoomYear1: 42000,
            annualTfsaIncrease: 7000,
            tfsaFundingSource: 'heloc',
            rrspYear1: 50000,
            rrspOngoing: 25000,
            rrspFundingSource: 'heloc',
            retirementTaxRate: 20,
            initialHelocAvailable: 300000,
        }),
    },
    {
        id: 'conservative',
        name: 'Conservative',
        icon: '🛡️',
        description: '$500K mortgage, low risk approach',
        formData: makePreset({
            initialMortgage: 500000,
            mortgageRate: 5.0,
            amortYears: 25,
            helocRate: 5.5,
            taxBracket: 'mid',
            annualReturn: 5,
            growthRate: 5,
            dividendYield: 2.5,
            initialTfsa: 0,
            tfsaRoomYear1: 20000,
            annualTfsaIncrease: 7000,
            tfsaFundingSource: 'savings',
            rrspYear1: 15000,
            rrspOngoing: 10000,
            rrspFundingSource: 'savings',
            retirementTaxRate: 20,
            initialHelocAvailable: 50000,
        }),
    },
    {
        id: 'aggressive',
        name: 'Aggressive',
        icon: '🚀',
        description: '$1.2M mortgage, max leverage',
        formData: makePreset({
            initialMortgage: 1200000,
            mortgageRate: 3.5,
            amortYears: 30,
            helocRate: 4.5,
            taxBracket: 'top',
            annualReturn: 9,
            growthRate: 9,
            dividendYield: 1.0,
            initialTfsa: 50000,
            tfsaRoomYear1: 42000,
            annualTfsaIncrease: 7000,
            tfsaFundingSource: 'heloc',
            rrspYear1: 60000,
            rrspOngoing: 30000,
            rrspFundingSource: 'heloc',
            retirementTaxRate: 20,
            initialHelocAvailable: 400000,
        }),
    },
    {
        id: 'high-income',
        name: 'High Income',
        icon: '💼',
        description: '$900K mortgage, large contributions',
        formData: makePreset({
            initialMortgage: 900000,
            mortgageRate: 4.0,
            amortYears: 25,
            helocRate: 5.0,
            taxBracket: 'top',
            annualReturn: 7,
            growthRate: 7,
            dividendYield: 1.6,
            initialTfsa: 30000,
            tfsaRoomYear1: 42000,
            annualTfsaIncrease: 7000,
            tfsaFundingSource: 'heloc',
            rrspYear1: 60000,
            rrspOngoing: 30000,
            rrspFundingSource: 'heloc',
            retirementTaxRate: 20,
            initialHelocAvailable: 200000,
        }),
    },
];
