import { getProvincialTaxRate } from '@/lib/provinceData';

// Helper to build a complete preset with tax rate auto-calculated
function makePreset(overrides) {
    const province = overrides.province || 'ON';
    const bracket = overrides.taxBracket || 'high';
    const taxRate = getProvincialTaxRate(province, bracket) || 48.35;

    return {
        initialMortgage: 500000,
        mortgageRate: 4.5,
        mortgageType: 'fixed',
        amortYears: 25,
        helocRate: 5.5,
        province: 'ON',
        taxBracket: 'high',
        taxRate,
        annualReturn: 7,
        growthRate: 7,
        dividendYield: 1.5,
        inflationRate: 2.0,
        initialTfsa: 0,
        tfsaRoomYear1: 7000,
        annualTfsaIncrease: 7000,
        tfsaFundingSource: 'savings',
        rrspYear1: 10000,
        rrspOngoing: 10000,
        rrspFundingSource: 'savings',
        retirementTaxRate: 20,
        initialHelocAvailable: 100000,
        // Optimization fields
        optimizationMode: 'classic',
        baseSalary: 100000,
        employerRrspMatch: 0,
        rrspRoomTotal: 50000,
        lumpSumAmount: 0,
        lumpSumYear: '1',
        prepaymentLimit: 15,
        ...overrides,
    };
}

export const PRESETS = [
    {
        id: 'vanilla-sm',
        name: 'Vanilla SM',
        icon: '🔄',
        description: 'Pure SM — no TFSA/RRSP, no initial HELOC',
        formData: makePreset({
            initialMortgage: 400000,
            mortgageRate: 5.0,
            amortYears: 25,
            helocRate: 6.0,
            taxBracket: 'high',
            annualReturn: 8,
            growthRate: 8,
            dividendYield: 2.0,
            initialTfsa: 0,
            tfsaRoomYear1: 0,
            annualTfsaIncrease: 0,
            tfsaFundingSource: 'savings',
            rrspYear1: 0,
            rrspOngoing: 0,
            rrspFundingSource: 'savings',
            retirementTaxRate: 20,
            initialHelocAvailable: 0,
            baseSalary: 100000,
            employerRrspMatch: 0,
            rrspRoomTotal: 0,
        }),
    },
    {
        id: 'first-time',
        name: 'First-Time Buyer',
        icon: '🏡',
        description: '$400K mortgage, limited savings, building from scratch',
        formData: makePreset({
            initialMortgage: 400000,
            mortgageRate: 5.0,
            amortYears: 25,
            helocRate: 5.5,
            taxBracket: 'mid',
            annualReturn: 7,
            growthRate: 7,
            dividendYield: 1.5,
            initialTfsa: 0,
            tfsaRoomYear1: 7000,
            annualTfsaIncrease: 7000,
            tfsaFundingSource: 'savings',
            rrspYear1: 5000,
            rrspOngoing: 5000,
            rrspFundingSource: 'savings',
            retirementTaxRate: 20,
            initialHelocAvailable: 50000,
            baseSalary: 75000,
            employerRrspMatch: 0,
            rrspRoomTotal: 30000,
        }),
    },
    {
        id: 'mid-career',
        name: 'Mid-Career Pro',
        icon: '💼',
        description: '$700K mortgage, decent equity, moderate leverage',
        formData: makePreset({
            initialMortgage: 700000,
            mortgageRate: 4.5,
            amortYears: 25,
            helocRate: 5.0,
            taxBracket: 'high',
            annualReturn: 7,
            growthRate: 7,
            dividendYield: 1.5,
            initialTfsa: 15000,
            tfsaRoomYear1: 21000,
            annualTfsaIncrease: 7000,
            tfsaFundingSource: 'savings',
            rrspYear1: 20000,
            rrspOngoing: 15000,
            rrspFundingSource: 'heloc',
            retirementTaxRate: 20,
            initialHelocAvailable: 150000,
            baseSalary: 120000,
            employerRrspMatch: 3,
            rrspRoomTotal: 80000,
        }),
    },
    {
        id: 'max-leverage',
        name: 'Max Leverage',
        icon: '🚀',
        description: '$1M mortgage, high income, maximizing everything',
        formData: makePreset({
            initialMortgage: 1000000,
            mortgageRate: 3.75,
            amortYears: 30,
            helocRate: 4.5,
            taxBracket: 'top',
            annualReturn: 8,
            growthRate: 8,
            dividendYield: 1.2,
            initialTfsa: 30000,
            tfsaRoomYear1: 42000,
            annualTfsaIncrease: 7000,
            tfsaFundingSource: 'heloc',
            rrspYear1: 50000,
            rrspOngoing: 30000,
            rrspFundingSource: 'heloc',
            retirementTaxRate: 20,
            initialHelocAvailable: 350000,
            baseSalary: 200000,
            employerRrspMatch: 5,
            rrspRoomTotal: 150000,
            lumpSumAmount: 50000,
            lumpSumYear: '1',
            prepaymentLimit: 10,
        }),
    },
    {
        id: 'conservative',
        name: 'Conservative',
        icon: '🛡️',
        description: '$400K mortgage, risk-averse, savings-only',
        formData: makePreset({
            initialMortgage: 400000,
            mortgageRate: 5.5,
            amortYears: 25,
            helocRate: 6.0,
            taxBracket: 'mid',
            annualReturn: 5,
            growthRate: 5,
            dividendYield: 3.0,
            initialTfsa: 0,
            tfsaRoomYear1: 7000,
            annualTfsaIncrease: 7000,
            tfsaFundingSource: 'savings',
            rrspYear1: 10000,
            rrspOngoing: 10000,
            rrspFundingSource: 'savings',
            retirementTaxRate: 20,
            initialHelocAvailable: 25000,
            baseSalary: 85000,
            employerRrspMatch: 0,
            rrspRoomTotal: 40000,
        }),
    },
    {
        id: 'rental-investor',
        name: 'Rental Investor',
        icon: '🏘️',
        description: '$800K mortgage, property-focused, minimal registered',
        formData: makePreset({
            initialMortgage: 800000,
            mortgageRate: 5.0,
            amortYears: 30,
            helocRate: 5.5,
            taxBracket: 'high',
            annualReturn: 7,
            growthRate: 8,
            dividendYield: 1.0,
            initialTfsa: 0,
            tfsaRoomYear1: 7000,
            annualTfsaIncrease: 7000,
            tfsaFundingSource: 'savings',
            rrspYear1: 0,
            rrspOngoing: 0,
            rrspFundingSource: 'savings',
            retirementTaxRate: 20,
            initialHelocAvailable: 200000,
            baseSalary: 130000,
            employerRrspMatch: 0,
            rrspRoomTotal: 0,
            prepaymentLimit: 20,
        }),
    },
];